version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    env_file: [.env]
    ports: ["3000:3000"]
    depends_on: [mongo, redis, neo4j]
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    ulimits:
      nofile: 65536

  mongo:
    image: mongo:6
    restart: unless-stopped
    ports: ["27017:27017"]
    volumes: [ "mongo_data:/data/db" ]

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports: ["6379:6379"]
    command: ["redis-server","--appendonly","yes"]
    volumes: [ "redis_data:/data" ]

  neo4j:
    image: neo4j:5.21
    restart: unless-stopped
    ports: ["7474:7474","7687:7687"]
    environment:
      NEO4J_AUTH: ${NEO4J_AUTH:-neo4j/test1234}
      NEO4J_PLUGINS: '["apoc","graph-data-science"]'
      NEO4J_dbms_security_procedures_unrestricted: "apoc.* , gds.*"
      NEO4J_dbms_security_procedures_allowlist: "apoc.* , gds.*"
    volumes:
      - neo4j_data:/data
      - neo4j_plugins:/plugins

volumes:
  mongo_data:
  redis_data:
  neo4j_data:
  neo4j_plugins:
