import type { CompanionContext, Round, Topic } from "./types";

/**
 * PR 01 manual-first baseline:
 * This seed file is the intentionally editable source for topic/round state
 * until persistent storage is introduced in later PRs.
 */
export const TOPIC_SEED: Topic[] = [
  {
    id: "topic-energy-berlin",
    slug: "bezahlbare-energie-und-waermewende-berlin",
    title: "Bezahlbare Energie und belastbare Wärmewende in Berlin",
    framingQuestion:
      "Wie sichern wir bezahlbare Heiz- und Stromkosten, ohne Klimaziele und Umsetzungstempo zu verlieren?",
    currentState:
      "Evidenzlage wächst, Konflikte zwischen Kostenstabilität und Ausbaupfaden sind sichtbar. Optionen liegen vor, aber noch nicht alle Auswirkungen sind belegt.",
    readiness: "options_clarifying",
    options: [
      {
        id: "opt-netz-sanierung",
        title: "Quartiersweise Netzsanierung priorisieren",
        summary: "Investitionen auf Gebiete mit hohem Einsparpotenzial fokussieren.",
      },
      {
        id: "opt-sozialtarif",
        title: "Sozialtarif mit Zielgruppe und Laufzeit begrenzen",
        summary: "Kurzfristige Entlastung koppeln an transparente Kriterien und Exit-Regeln.",
      },
      {
        id: "opt-transparenz-dashboard",
        title: "Monatliches Kosten- und Fortschrittsdashboard",
        summary: "Umsetzung, Risiken und Preiswirkung pro Projekt offenlegen.",
      },
    ],
    claims: [
      {
        id: "clm-1",
        text: "Unsanierte Teilnetze verursachen überproportionale Betriebskosten und stören die Preisstabilität.",
        sourceIds: ["src-1", "src-3"],
      },
      {
        id: "clm-2",
        text: "Ein befristeter Sozialtarif reduziert kurzfristige Ausfallrisiken bei besonders belasteten Haushalten.",
        sourceIds: ["src-2"],
      },
      {
        id: "clm-3",
        text: "Fehlende Transparenz zu Projektfortschritt und Kosten erzeugt Vertrauensverlust in der Bevölkerung.",
        sourceIds: ["src-4"],
      },
    ],
    sources: [
      {
        id: "src-1",
        title: "Netzzustandsbericht Wärme 2025",
        url: "https://example.org/netzbericht-waerme-2025",
        publisher: "Landesenergieagentur",
        sourceClass: "official_document",
      },
      {
        id: "src-2",
        title: "Sozialmonitor Energiearmut Q4/2025",
        url: "https://example.org/sozialmonitor-energiearmut",
        publisher: "Sozialamt Berlin",
        sourceClass: "secondary_report",
      },
      {
        id: "src-3",
        title: "Praxisanalyse Fernwärmeausfälle 2024",
        url: "https://example.org/fernwaerme-ausfaelle-2024",
        publisher: "Stadtwerke Verbund",
        sourceClass: "primary_source",
      },
      {
        id: "src-4",
        title: "Befragung Vertrauen in Energieprojekte 2025",
        url: "https://example.org/vertrauen-energieprojekte-2025",
        publisher: "Bürgerpanel Berlin",
        sourceClass: "community_note",
      },
    ],
    objections: [
      "Die Kostenprognosen der Netzsanierung unterschätzen Material- und Fachkräftepreisrisiken.",
      "Ein pauschaler Sozialtarif kann Fehlanreize setzen, wenn Zielgruppen nicht präzise begrenzt sind.",
      "Ein Dashboard ohne belastbare Rohdaten verbessert Transparenz nicht ausreichend.",
    ],
    openQuestions: [
      "Welche Quartiere liefern in 24 Monaten den größten Effekt pro investiertem Euro?",
      "Welche Kriterien definieren den Zugang zum Sozialtarif nachvollziehbar und prüfbar?",
      "Welche Stelle verantwortet monatliche Datengüte für das Fortschrittsdashboard?",
    ],
    roadmap: [
      {
        id: "rm-1",
        category: "evidence_missing",
        title: "Kostenvergleich nach Quartier vervollständigen",
        unresolved: "Belastbare Vergleichswerte für drei priorisierte Quartiere fehlen.",
        evidenceMissing: "Vollkosten inkl. Bauzeitrisiko und Betriebskostenprojektion.",
        askNext: "Welche Quartierliste ist für 2026 zuerst finanzierbar?",
        responderHint: "Landesenergieagentur + Stadtwerke",
        voteReadinessSignal: "review_needed",
        status: "open",
      },
      {
        id: "rm-2",
        category: "counterposition_missing",
        title: "Gegenposition zum Sozialtarif strukturiert aufnehmen",
        unresolved: "Kontra-Argumente sind fragmentiert und nicht vergleichbar dokumentiert.",
        askNext: "Welche Alternativen zum Sozialtarif haben messbare Armutswirkung?",
        responderHint: "Sozialverwaltung + Verbraucherschutz",
        voteReadinessSignal: "review_needed",
        status: "in_progress",
      },
      {
        id: "rm-3",
        category: "authority_response_needed",
        title: "Zuständigkeitsantwort für Dashboard-Pflege klären",
        unresolved: "Datenpflegeverantwortung zwischen Senatsverwaltung und Stadtwerken ist offen.",
        askNext: "Wer veröffentlicht monatlich den verbindlichen Datensatz?",
        responderHint: "Senatsverwaltung",
        voteReadinessSignal: "not_ready",
        status: "blocked",
      },
      {
        id: "rm-4",
        category: "ready_for_vote_check",
        title: "Vorprüfung zur Abstimmungsreife vorbereiten",
        unresolved: "Optionen sind noch nicht mit identischen Kennzahlen hinterlegt.",
        askNext: "Welche Mindestkriterien müssen vor einem Vote-Check erfüllt sein?",
        responderHint: "Moderation + Redaktion",
        voteReadinessSignal: "review_needed",
        status: "open",
      },
    ],
    conflicts: [
      {
        id: "cf-1",
        kind: "evidence_conflict",
        title: "Kostenkonflikt zwischen Netzbericht und Praxisanalyse",
        details:
          "Investitions- und Betriebskosten laufen je Quartier auseinander. Die Vergleichbarkeit der Annahmen ist aktuell nicht ausreichend dokumentiert.",
        relatedClaimIds: ["clm-1"],
        relatedSourceIds: ["src-1", "src-3"],
        unresolved: true,
      },
      {
        id: "cf-2",
        kind: "option_disagreement",
        title: "Sozialtarif: Entlastung vs. Fehlanreiz",
        details:
          "Ein Teil der Beiträge fordert schnelle Entlastung, ein anderer Teil bewertet die Zielgruppenschärfe und Exit-Regeln als nicht belastbar genug.",
        relatedClaimIds: ["clm-2"],
        relatedOptionIds: ["opt-sozialtarif"],
        unresolved: true,
      },
      {
        id: "cf-3",
        kind: "counterposition_missing",
        title: "Counterposition zum Dashboard-Pfad ist unvollständig",
        details:
          "Die Kritik an Datenqualität ist sichtbar, aber eine ausformulierte Gegenalternative zur monatlichen Publikation fehlt.",
        relatedClaimIds: ["clm-3"],
        unresolved: true,
      },
    ],
    reviewLog: [
      {
        id: "rl-1",
        status: "submitted",
        scope: "round_contribution",
        entityId: "rc-10",
        title: "Datendefinitionstabelle eingereicht",
        summary: "Beitrag aus Verwaltungs-Session wurde als Quelle für Dashboard-Standards eingereicht.",
        sourceRoundSlug: "verwaltungssession-datenstandard",
        publicReason: "Neues Material für Evidenz- und Umsetzungsprüfung.",
        internalReason: "Schema passt, semantische Felder noch zu normalisieren.",
        reviewedBy: "moderation@edebatte.local",
        reviewedAt: "2026-02-20T11:10:00.000Z",
        visibility: "public",
      },
      {
        id: "rl-2",
        status: "under_review",
        scope: "merge_suggestion",
        entityId: "ras-merge-1",
        title: "AI-Hinweis zu Claim-Clustering in Review",
        summary: "Assist-Vorschlag wird manuell mit bestehendem Claim clm-1 abgeglichen.",
        sourceRoundSlug: "livestream-qa-stadtwerke",
        publicReason: "Mögliche Dublette wird vor Merge transparent geprüft.",
        internalReason: "Potenzieller Doppelpunkt; erst nach Redaktionsabgleich entscheiden.",
        reviewedBy: "editor@edebatte.local",
        reviewedAt: "2026-02-05T09:30:00.000Z",
        visibility: "management_only",
      },
      {
        id: "rl-3",
        status: "merged_into_existing_item",
        scope: "roadmap_action",
        entityId: "rm-2",
        title: "Counterposition-Task mit Session-Input zusammengeführt",
        summary: "Fragen aus Eventrunde wurden in Roadmap-Item rm-2 integriert.",
        sourceRoundSlug: "vor-ort-forum-energiepreise-neukoelln",
        appliedToId: "rm-2",
        publicReason: "Doppelte Folgefrage vermieden, bestehendes Item erweitert.",
        internalReason: "Gleicher inhaltlicher Schwerpunkt, zusammengeführt für bessere Nachverfolgbarkeit.",
        reviewedBy: "moderation@edebatte.local",
        reviewedAt: "2026-01-27T08:40:00.000Z",
        visibility: "public",
      },
      {
        id: "rl-4",
        status: "deferred_to_next_round",
        scope: "round_contribution",
        entityId: "rc-11",
        title: "Priorisierungsliste auf nächste Open Round vertagt",
        summary: "Follow-up-Task bleibt offen bis Evidenzmatrix aus Session vervollständigt ist.",
        sourceRoundSlug: "offene-runde-naechster-fokus",
        publicReason: "Entscheidung auf nächste Runde verschoben, um Datenlücken zu schließen.",
        internalReason: "Abhängig von externer Datennachreichung.",
        reviewedBy: "moderation@edebatte.local",
        reviewedAt: "2026-03-05T08:25:00.000Z",
        visibility: "public",
      },
      {
        id: "rl-5",
        status: "accepted_as_new_draft",
        scope: "claim_update",
        entityId: "clm-draft-4",
        title: "Neuer Claim-Entwurf zu Finanzierungspuffer",
        summary: "Rundenbeitrag wurde als neuer Draft-Claim in die interne Review übernommen.",
        sourceRoundSlug: "podcast-expertenrunde-netzausbau",
        publicReason: "Neue Perspektive aufgenommen, noch nicht final verifiziert.",
        internalReason: "Sourcing läuft, final erst nach Gegenposition.",
        reviewedBy: "redaktion@edebatte.local",
        reviewedAt: "2026-02-12T10:10:00.000Z",
        visibility: "management_only",
      },
    ],
    readinessChecks: [
      {
        id: "ready-1",
        createdAt: "2026-03-06T10:00:00.000Z",
        decidedBy: "moderation-board",
        decision: "needs_next_round",
        rationale:
          "Vote-Check wird erst empfohlen, wenn Kostenvergleich pro Quartier und Counterposition zum Sozialtarif geschlossen sind.",
      },
    ],
    exportSnapshot: {
      conciseSummary:
        "Topic im Status options_clarifying. Hauptkonflikte liegen bei Kostenannahmen, Sozialtarif-Kriterien und Verantwortlichkeit für Dashboard-Daten.",
      nextRoundAgenda: [
        "Kostenannahmen aus src-1 und src-3 harmonisieren",
        "Counterpositionen zum Sozialtarif strukturiert gegenüberstellen",
        "Verbindliche Datenzuständigkeit für Dashboard festlegen",
      ],
      sourceSnapshot: [
        "src-1 official_document: Netzzustandsbericht Wärme 2025",
        "src-2 secondary_report: Sozialmonitor Energiearmut",
        "src-3 primary_source: Praxisanalyse Fernwärmeausfälle",
        "src-4 community_note: Bürgerpanel Vertrauen",
      ],
      roadmapSnapshot: [
        "rm-1 open evidence_missing",
        "rm-2 in_progress counterposition_missing",
        "rm-3 blocked authority_response_needed",
        "rm-4 open ready_for_vote_check",
      ],
      handoffNote:
        "Mandat-Handoff erst nach nächster Runde und dokumentierter Verantwortlichkeitszusage für Datengüte empfohlen.",
    },
    mandateBridge: {
      clarifiedNow: [
        "Prioritäre Quartiere für Netzsanierung sind eingegrenzt",
        "Mindestindikatoren für Sozialtarif-Pilot sind benannt",
      ],
      ownerNeeded: [
        "Verbindliche Datenpflege-Stelle für Dashboard",
        "Verantwortliche Stelle für Sozialtarif-Evaluation",
      ],
      openBeforeImplementation: [
        "Finanzierungspuffer bei steigenden Zinsen",
        "Counterpositionen zur Zielgruppendefinition",
      ],
      monitoringFocus: [
        "Ausfallquote je Quartier",
        "Haushaltsentlastung pro Zielgruppe",
        "Datenqualität und Publikationsrhythmus",
      ],
      linkedMandateId: "mandate-energy-berlin-2026-q2",
    },
  },
];

export const ROUND_SEED: Round[] = [
  {
    id: "rnd-article-1",
    slug: "artikel-kostenanalyse-waermenetze",
    topicSlug: "bezahlbare-energie-und-waermewende-berlin",
    title: "Artikelrunde: Kostenanalyse Wärmenetze",
    type: "article",
    status: "closed",
    startedAt: "2026-01-18T09:00:00.000Z",
    sourceLabel: "Hintergrundartikel",
    sourceUrl: "https://example.org/artikel-waermenetze-kostenanalyse",
    sourcePublisher: "Lokalredaktion Berlin",
    summary:
      "Der Artikel hat Netzverluste und Investitionsstau für drei Quartiere offengelegt. Schwerpunkt war Kostenentwicklung je Haushalt.",
    openPoints: [
      "Kostenannahmen für Materialpreise müssen aktualisiert werden.",
      "Vergleichsdaten zu alternativen Sanierungsfolgen fehlen.",
    ],
    contributions: [
      {
        id: "rc-1",
        type: "source",
        text: "Ergänzender Verweis auf den Netzzustandsbericht 2025 mit Datentabelle pro Quartier.",
        authorLabel: "Bürgerbeitrag",
        createdAt: "2026-01-18T11:20:00.000Z",
        reviewStatus: "merged_into_existing_item",
      },
      {
        id: "rc-2",
        type: "question",
        text: "Warum unterscheiden sich die Betriebskostenprognosen zwischen Nord und Ost so stark?",
        authorLabel: "Journalismus",
        createdAt: "2026-01-18T12:10:00.000Z",
        reviewStatus: "under_review",
      },
      {
        id: "rc-3",
        type: "objection",
        text: "Die angenommene Bauzeit wirkt zu optimistisch und ignoriert Engpässe bei Fachfirmen.",
        authorLabel: "Fachverband Handwerk",
        createdAt: "2026-01-18T12:45:00.000Z",
        reviewStatus: "accepted_as_new_draft",
      },
    ],
  },
  {
    id: "rnd-event-1",
    slug: "vor-ort-forum-energiepreise-neukoelln",
    topicSlug: "bezahlbare-energie-und-waermewende-berlin",
    title: "Eventrunde: Vor-Ort-Forum Energiepreise in Neukölln",
    type: "event",
    status: "closed",
    startedAt: "2026-01-25T16:30:00.000Z",
    sourceLabel: "Öffentliches Forum",
    sourcePublisher: "Bezirksamt Neukölln",
    summary:
      "Im Forum wurden Belastungsspitzen bei Mietnebenkosten gesammelt und priorisiert. Verwaltung und Stadtwerke haben offene Punkte mitgenommen.",
    openPoints: [
      "Definition für haushaltsnahe Entlastungsgrenzen fehlt.",
      "Rolle der Bezirke bei Zielgruppenansprache muss geklärt werden.",
    ],
    contributions: [
      {
        id: "rc-4",
        type: "perspective",
        text: "Viele Familien berichten über stark schwankende Abschläge trotz konstantem Verbrauch.",
        authorLabel: "Bewohnerinitiative",
        createdAt: "2026-01-25T18:10:00.000Z",
        reviewStatus: "accepted_as_new_draft",
      },
      {
        id: "rc-5",
        type: "option",
        text: "Pilot mit quartiersbezogenem Sozialtarif plus verpflichtender Energieberatung.",
        authorLabel: "Sozialträger",
        createdAt: "2026-01-25T19:05:00.000Z",
        reviewStatus: "merged_into_existing_item",
      },
    ],
  },
  {
    id: "rnd-livestream-1",
    slug: "livestream-qa-stadtwerke",
    topicSlug: "bezahlbare-energie-und-waermewende-berlin",
    title: "Livestreamrunde: Q&A mit Stadtwerken",
    type: "livestream",
    status: "closed",
    startedAt: "2026-02-02T18:00:00.000Z",
    sourceLabel: "Livestream",
    sourceUrl: "https://example.org/livestream-stadtwerke-qa",
    sourcePublisher: "Stadtwerke Berlin",
    summary:
      "Im Livestream wurden Bauablauf, Ausfallrisiken und geplante Transparenzmaßnahmen diskutiert. Mehrere Punkte wurden zur Nachprüfung markiert.",
    openPoints: [
      "Verbindliche Termine für monatliche Datenschnittstellen fehlen.",
      "Antwort zu Finanzierungspuffer ist unvollständig.",
    ],
    contributions: [
      {
        id: "rc-6",
        type: "summary_note",
        text: "Zentraler Konsens: Transparenz über Baustufen ist wichtiger als ein einzelner Endtermin.",
        authorLabel: "Moderation",
        createdAt: "2026-02-02T19:45:00.000Z",
        reviewStatus: "accepted_as_new_draft",
      },
      {
        id: "rc-7",
        type: "followup_task",
        text: "Stadtwerke liefern bis nächste Woche einen Datenfeldkatalog für das Fortschrittsdashboard.",
        authorLabel: "Redaktion",
        createdAt: "2026-02-02T19:52:00.000Z",
        reviewStatus: "under_review",
      },
    ],
  },
  {
    id: "rnd-video-1",
    slug: "video-erklaerung-sozialtarif",
    topicSlug: "bezahlbare-energie-und-waermewende-berlin",
    title: "Videorunde: Erklärstück Sozialtarif",
    type: "video",
    status: "closed",
    startedAt: "2026-02-07T08:30:00.000Z",
    sourceLabel: "Kurzvideo",
    sourceUrl: "https://example.org/video-sozialtarif-erklaert",
    sourcePublisher: "Kommunalkanal",
    summary:
      "Das Video hat Kriterien und Kritikpunkte zum Sozialtarif erklärt. In der Diskussion wurden mehrere Messindikatoren gefordert.",
    openPoints: [
      "Wie wird Mitnahmeeffekt im Pilot belastbar gemessen?",
      "Welche Exit-Regel gilt nach Ablauf der Pilotphase?",
    ],
    contributions: [
      {
        id: "rc-8",
        type: "protocol_note",
        text: "Diskussion protokolliert drei Mindestindikatoren: Ausfallquote, Haushaltsentlastung, Beratungsquote.",
        authorLabel: "Protokollteam",
        createdAt: "2026-02-07T10:05:00.000Z",
        reviewStatus: "merged_into_existing_item",
      },
    ],
  },
  {
    id: "rnd-podcast-1",
    slug: "podcast-expertenrunde-netzausbau",
    topicSlug: "bezahlbare-energie-und-waermewende-berlin",
    title: "Podcastrunde: Expertenrunde Netzausbau",
    type: "podcast",
    status: "closed",
    startedAt: "2026-02-11T13:00:00.000Z",
    sourceLabel: "Podcast Episode",
    sourceUrl: "https://example.org/podcast-netzausbau",
    sourcePublisher: "Stadtgespräche",
    summary:
      "Fachgäste haben Ausbaupfade, Finanzierungsmodelle und Verteilwirkungen gegenübergestellt.",
    openPoints: [
      "Wie werden Randlagen in Priorisierung transparent berücksichtigt?",
    ],
    contributions: [
      {
        id: "rc-9",
        type: "question",
        text: "Welche Finanzierungsmischung bleibt stabil, wenn Zinsszenarien steigen?",
        authorLabel: "Publikum",
        createdAt: "2026-02-11T14:20:00.000Z",
        reviewStatus: "accepted_as_new_draft",
      },
    ],
  },
  {
    id: "rnd-session-1",
    slug: "verwaltungssession-datenstandard",
    topicSlug: "bezahlbare-energie-und-waermewende-berlin",
    title: "Sessionrunde: Verwaltungsworkshop Datenstandard",
    type: "session",
    status: "open",
    startedAt: "2026-02-20T09:00:00.000Z",
    sourceLabel: "Fachsession",
    sourcePublisher: "Senatsverwaltung",
    summary:
      "Arbeitsgruppe zu Datenqualität und Reportingzyklen für das Topic-Dashboard. Runde ist noch offen für Nachreichungen.",
    openPoints: [
      "Versionierungsregel für Korrekturen muss festgelegt werden.",
      "Publikationsrhythmus über Feiertage ist offen.",
    ],
    contributions: [
      {
        id: "rc-10",
        type: "source",
        text: "Entwurf einer Datendefinitionstabelle mit Feldbeschreibungen und Validierungsregeln.",
        authorLabel: "IT-Leitstelle",
        createdAt: "2026-02-20T10:15:00.000Z",
        reviewStatus: "submitted",
      },
    ],
  },
  {
    id: "rnd-open-1",
    slug: "offene-runde-naechster-fokus",
    topicSlug: "bezahlbare-energie-und-waermewende-berlin",
    title: "Open Round: Nächster Fokus für das Topic",
    type: "open_round",
    status: "open",
    startedAt: "2026-03-04T17:30:00.000Z",
    sourceLabel: "Offene Beteiligungsrunde",
    summary:
      "Offene Runde für die Frage, welche Evidenz vor einem Vote-Check zwingend noch nachgereicht werden muss.",
    openPoints: [
      "Priorisierung der fehlenden Evidenz ist noch nicht abgeschlossen.",
      "Counterpositionen zum Sozialtarif müssen konsolidiert werden.",
    ],
    contributions: [
      {
        id: "rc-11",
        type: "followup_task",
        text: "Moderation erstellt bis zur nächsten Woche eine priorisierte Evidenzliste für den Vote-Check.",
        authorLabel: "Moderation",
        createdAt: "2026-03-04T19:00:00.000Z",
        reviewStatus: "deferred_to_next_round",
      },
    ],
  },
];

export const COMPANION_CONTEXT_SEED: CompanionContext[] = [
  {
    id: "cmp-article-waermenetze",
    slug: "bezahlbare-energie-berlin-artikel-kostenanalyse",
    type: "article",
    title: "Begleitraum zum Artikel: Kostenanalyse Wärmenetze",
    medium: "Lokalredaktion Berlin",
    format: "Hintergrundartikel",
    author: "Redaktion Energie & Stadt",
    editorialOwner: "Lokalredaktion Berlin",
    publishedAt: "2026-01-18T09:00:00.000Z",
    issue: "Ausgabe 03/2026",
    reference: "Wärmenetze in Berlin: Wer trägt die Kosten?",
    intro:
      "Dieser Begleitraum bündelt Fragen und Einwände direkt aus dem Artikelkontext, bevor der breite Themenraum geöffnet wird.",
    visibility: "semi_open",
    accessPolicy: "context_first_then_topic",
    linkedTopicSlug: "bezahlbare-energie-und-waermewende-berlin",
    linkedRoundSlug: "artikel-kostenanalyse-waermenetze",
    qrTargetPath: "/companion/bezahlbare-energie-berlin-artikel-kostenanalyse?entry=qr&source=article",
    canonicalOpenPath: "/topic/bezahlbare-energie-und-waermewende-berlin",
    moderationMode: "moderated_public",
    mainQuestion:
      "Welche Annahmen aus dem Artikel müssen zuerst geprüft werden, bevor wir über Prioritäten abstimmen?",
  },
  {
    id: "cmp-tv-energiecheck",
    slug: "bezahlbare-energie-berlin-tv-energiecheck",
    type: "tv_show",
    title: "Begleitraum zur TV-Sendung: Energiecheck Berlin",
    medium: "StadtTV",
    format: "TV-Sendung",
    host: "Mina Weber",
    editorialOwner: "StadtTV Debatte",
    publishedAt: "2026-02-03T20:15:00.000Z",
    episode: "Folge 12",
    reference: "Energiepreise, Netzausbau und Sozialtarif",
    intro:
      "Hier werden Aussagen aus der Sendung gesammelt und präzisiert. Der offene Topic-Raum folgt als nächster Schritt.",
    visibility: "exclusive",
    accessPolicy: "qr_only",
    linkedTopicSlug: "bezahlbare-energie-und-waermewende-berlin",
    linkedRoundSlug: "livestream-qa-stadtwerke",
    qrTargetPath: "/companion/bezahlbare-energie-berlin-tv-energiecheck?entry=qr&source=tv_show",
    canonicalOpenPath: "/topic/bezahlbare-energie-und-waermewende-berlin",
    moderationMode: "editorial_gate",
    mainQuestion:
      "Welche Aussagen aus der Sendung sind belastbar belegt, welche müssen im offenen Thema nachrecherchiert werden?",
  },
  {
    id: "cmp-podcast-netzausbau",
    slug: "bezahlbare-energie-berlin-podcast-netzausbau",
    type: "podcast",
    title: "Begleitraum zur Podcast-Episode: Expertenrunde Netzausbau",
    medium: "Stadtgespräche",
    format: "Podcast",
    host: "Daniel K.",
    editorialOwner: "Stadtgespräche Redaktion",
    publishedAt: "2026-02-11T13:00:00.000Z",
    episode: "Episode 44",
    reference: "Finanzierung und Verteilwirkungen",
    intro:
      "Dieser Raum hält Einwände und Nachfragen zur Episode zusammen und führt danach in den allgemeinen Themenraum.",
    visibility: "semi_open",
    accessPolicy: "context_first_then_topic",
    linkedTopicSlug: "bezahlbare-energie-und-waermewende-berlin",
    linkedRoundSlug: "podcast-expertenrunde-netzausbau",
    qrTargetPath: "/companion/bezahlbare-energie-berlin-podcast-netzausbau?entry=qr&source=podcast",
    canonicalOpenPath: "/topic/bezahlbare-energie-und-waermewende-berlin",
    moderationMode: "moderated_public",
    mainQuestion:
      "Welche Finanzierungsannahmen aus der Episode sind für den nächsten Roadmap-Schritt entscheidend?",
  },
  {
    id: "cmp-print-rubrik",
    slug: "bezahlbare-energie-berlin-print-rubrik-waermewende",
    type: "print",
    title: "Begleitraum zur Printausgabe: Rubrik Wärmewende",
    medium: "Stadtjournal",
    format: "Print",
    editorialOwner: "Stadtjournal Redaktion",
    publishedAt: "2026-02-14T06:00:00.000Z",
    issue: "Ausgabe 07/2026",
    page: "S. 8-9",
    reference: "Rubrik Wärmewende",
    intro:
      "Dieser Begleitraum sammelt Rückmeldungen zur konkreten Printseite, bevor Beiträge in den offenen Topic-Bereich wechseln.",
    visibility: "exclusive",
    accessPolicy: "link_required",
    linkedTopicSlug: "bezahlbare-energie-und-waermewende-berlin",
    qrTargetPath: "/companion/bezahlbare-energie-berlin-print-rubrik-waermewende?entry=qr&source=print",
    canonicalOpenPath: "/topic/bezahlbare-energie-und-waermewende-berlin",
    moderationMode: "public_with_review",
    mainQuestion:
      "Welche offenen Punkte aus der Print-Rubrik sollen zuerst im Dossier des Themas vertieft werden?",
  },
  {
    id: "cmp-leserbrief-entlastung",
    slug: "bezahlbare-energie-berlin-leserbrief-entlastung",
    type: "letter_to_editor",
    title: "Begleitraum zum Leserbrief: Entlastung und Fairness",
    medium: "Lokalredaktion Berlin",
    format: "Leserbrief",
    author: "Leserbriefredaktion",
    editorialOwner: "Lokalredaktion Berlin",
    publishedAt: "2026-02-22T08:00:00.000Z",
    reference: "Leserbrief #312",
    intro:
      "Dieser Raum bleibt eng am eingereichten Anlass und öffnet erst danach in den allgemeinen Topic-Kontext.",
    visibility: "semi_open",
    accessPolicy: "context_first_then_topic",
    linkedTopicSlug: "bezahlbare-energie-und-waermewende-berlin",
    qrTargetPath: "/companion/bezahlbare-energie-berlin-leserbrief-entlastung?entry=qr&source=letter_to_editor",
    canonicalOpenPath: "/topic/bezahlbare-energie-und-waermewende-berlin",
    moderationMode: "moderated_public",
    mainQuestion:
      "Welche konkreten Einwände aus dem Leserbrief müssen in die nächste Round übernommen werden?",
  },
  {
    id: "cmp-event-neukoelln",
    slug: "bezahlbare-energie-berlin-event-neukoelln",
    type: "event",
    title: "Begleitraum zum Vor-Ort-Forum in Neukölln",
    medium: "Bezirksamt Neukölln",
    format: "Veranstaltung",
    host: "Moderation Bezirksdialog",
    editorialOwner: "Bezirksamt Neukölln",
    publishedAt: "2026-01-25T16:30:00.000Z",
    reference: "Forum Energiepreise",
    intro:
      "Hier starten Teilnehmende aus dem Eventkontext. Aus diesem Anlassraum geht es später in das offene Topic.",
    visibility: "semi_open",
    accessPolicy: "context_first_then_topic",
    linkedTopicSlug: "bezahlbare-energie-und-waermewende-berlin",
    linkedRoundSlug: "vor-ort-forum-energiepreise-neukoelln",
    qrTargetPath: "/companion/bezahlbare-energie-berlin-event-neukoelln?entry=qr&source=event",
    canonicalOpenPath: "/topic/bezahlbare-energie-und-waermewende-berlin",
    moderationMode: "moderated_public",
    mainQuestion:
      "Welche Belastungsspitzen aus dem Forum sind am dringendsten und wie fließen sie in die Topic-Roadmap ein?",
  },
];
