import type { Round, Topic } from "./types";

/**
 * PR 01 manual-first baseline:
 * This seed file is the intentionally editable source for topic/round state
 * until persistent storage is introduced in later PRs.
 */
export const TOPIC_SEED: Topic[] = [
  {
    id: "topic-energy-berlin",
    slug: "bezahlbare-energie-und-waermewende-berlin",
    title: "Bezahlbare Energie und belastbare Waermewende in Berlin",
    framingQuestion:
      "Wie sichern wir bezahlbare Heiz- und Stromkosten, ohne Klimaziele und Umsetzungstempo zu verlieren?",
    currentState:
      "Evidenzlage waechst, Konflikte zwischen Kostenstabilitaet und Ausbaupfaden sind sichtbar. Optionen liegen vor, aber noch nicht alle Auswirkungen sind belegt.",
    readiness: "options_clarifying",
    options: [
      {
        id: "opt-netz-sanierung",
        title: "Quartiersweise Netzsanierung priorisieren",
        summary: "Investitionen auf Gebiete mit hohem Einsparpotenzial fokussieren.",
      },
      {
        id: "opt-sozialtarif",
        title: "Sozialtarif mit Zielgruppe und Laufzeit begrenzen",
        summary: "Kurzfristige Entlastung koppeln an transparente Kriterien und Exit-Regeln.",
      },
      {
        id: "opt-transparenz-dashboard",
        title: "Monatliches Kosten- und Fortschrittsdashboard",
        summary: "Umsetzung, Risiken und Preiswirkung pro Projekt offenlegen.",
      },
    ],
    claims: [
      {
        id: "clm-1",
        text: "Unsanierte Teilnetze verursachen ueberproportionale Betriebskosten und stoeren die Preisstabilitaet.",
        sourceIds: ["src-1", "src-3"],
      },
      {
        id: "clm-2",
        text: "Ein befristeter Sozialtarif reduziert kurzfristige Ausfallrisiken bei besonders belasteten Haushalten.",
        sourceIds: ["src-2"],
      },
      {
        id: "clm-3",
        text: "Fehlende Transparenz zu Projektfortschritt und Kosten erzeugt Vertrauensverlust in der Bevoelkerung.",
        sourceIds: ["src-4"],
      },
    ],
    sources: [
      {
        id: "src-1",
        title: "Netzzustandsbericht Waerme 2025",
        url: "https://example.org/netzbericht-waerme-2025",
        publisher: "Landesenergieagentur",
        sourceClass: "official_document",
      },
      {
        id: "src-2",
        title: "Sozialmonitor Energiearmut Q4/2025",
        url: "https://example.org/sozialmonitor-energiearmut",
        publisher: "Sozialamt Berlin",
        sourceClass: "secondary_report",
      },
      {
        id: "src-3",
        title: "Praxisanalyse Fernwaermeausfaelle 2024",
        url: "https://example.org/fernwaerme-ausfaelle-2024",
        publisher: "Stadtwerke Verbund",
        sourceClass: "primary_source",
      },
      {
        id: "src-4",
        title: "Befragung Vertrauen in Energieprojekte 2025",
        url: "https://example.org/vertrauen-energieprojekte-2025",
        publisher: "Buergerpanel Berlin",
        sourceClass: "community_note",
      },
    ],
    objections: [
      "Die Kostenprognosen der Netzsanierung unterschaetzen Material- und Fachkraeftepreisrisiken.",
      "Ein pauschaler Sozialtarif kann Fehlanreize setzen, wenn Zielgruppen nicht praezise begrenzt sind.",
      "Ein Dashboard ohne belastbare Rohdaten verbessert Transparenz nicht ausreichend.",
    ],
    openQuestions: [
      "Welche Quartiere liefern in 24 Monaten den groessten Effekt pro investiertem Euro?",
      "Welche Kriterien definieren den Zugang zum Sozialtarif nachvollziehbar und pruefbar?",
      "Welche Stelle verantwortet monatliche Datenguete fuer das Fortschrittsdashboard?",
    ],
    roadmap: [
      {
        id: "rm-1",
        category: "evidence_missing",
        title: "Kostenvergleich nach Quartier vervollstaendigen",
        unresolved: "Belastbare Vergleichswerte fuer drei priorisierte Quartiere fehlen.",
        evidenceMissing: "Vollkosten inkl. Bauzeitrisiko und Betriebskostenprojektion.",
        askNext: "Welche Quartierliste ist fuer 2026 zuerst finanzierbar?",
        responderHint: "Landesenergieagentur + Stadtwerke",
        voteReadinessSignal: "review_needed",
        status: "open",
      },
      {
        id: "rm-2",
        category: "counterposition_missing",
        title: "Gegenposition zum Sozialtarif strukturiert aufnehmen",
        unresolved: "Kontra-Argumente sind fragmentiert und nicht vergleichbar dokumentiert.",
        askNext: "Welche Alternativen zum Sozialtarif haben messbare Armutswirkung?",
        responderHint: "Sozialverwaltung + Verbraucherschutz",
        voteReadinessSignal: "review_needed",
        status: "in_progress",
      },
      {
        id: "rm-3",
        category: "authority_response_needed",
        title: "Zustaendigkeitsantwort fuer Dashboard-Pflege klaeren",
        unresolved: "Datenpflegeverantwortung zwischen Senatsverwaltung und Stadtwerken ist offen.",
        askNext: "Wer veroeffentlicht monatlich den verbindlichen Datensatz?",
        responderHint: "Senatsverwaltung",
        voteReadinessSignal: "not_ready",
        status: "blocked",
      },
      {
        id: "rm-4",
        category: "ready_for_vote_check",
        title: "Vorpruefung zur Abstimmungsreife vorbereiten",
        unresolved: "Optionen sind noch nicht mit identischen Kennzahlen hinterlegt.",
        askNext: "Welche Mindestkriterien muessen vor einem Vote-Check erfuellt sein?",
        responderHint: "Moderation + Redaktion",
        voteReadinessSignal: "review_needed",
        status: "open",
      },
    ],
    conflicts: [
      {
        id: "cf-1",
        kind: "evidence_conflict",
        title: "Kostenkonflikt zwischen Netzbericht und Praxisanalyse",
        details:
          "Investitions- und Betriebskosten laufen je Quartier auseinander. Die Vergleichbarkeit der Annahmen ist aktuell nicht ausreichend dokumentiert.",
        relatedClaimIds: ["clm-1"],
        relatedSourceIds: ["src-1", "src-3"],
        unresolved: true,
      },
      {
        id: "cf-2",
        kind: "option_disagreement",
        title: "Sozialtarif: Entlastung vs. Fehlanreiz",
        details:
          "Ein Teil der Beitraege fordert schnelle Entlastung, ein anderer Teil bewertet die Zielgruppenschaerfe und Exit-Regeln als nicht belastbar genug.",
        relatedClaimIds: ["clm-2"],
        relatedOptionIds: ["opt-sozialtarif"],
        unresolved: true,
      },
      {
        id: "cf-3",
        kind: "counterposition_missing",
        title: "Counterposition zum Dashboard-Pfad ist unvollstaendig",
        details:
          "Die Kritik an Datenqualitaet ist sichtbar, aber eine ausformulierte Gegenalternative zur monatlichen Publikation fehlt.",
        relatedClaimIds: ["clm-3"],
        unresolved: true,
      },
    ],
    reviewLog: [
      {
        id: "rl-1",
        status: "submitted",
        scope: "round_contribution",
        entityId: "rc-10",
        title: "Datendefinitionstabelle eingereicht",
        summary: "Beitrag aus Verwaltungs-Session wurde als Quelle fuer Dashboard-Standards eingereicht.",
        sourceRoundSlug: "verwaltungssession-datenstandard",
        publicReason: "Neues Material fuer Evidenz- und Umsetzungspruefung.",
        internalReason: "Schema passt, semantische Felder noch zu normalisieren.",
        reviewedBy: "moderation@edebatte.local",
        reviewedAt: "2026-02-20T11:10:00.000Z",
        visibility: "public",
      },
      {
        id: "rl-2",
        status: "under_review",
        scope: "merge_suggestion",
        entityId: "ras-merge-1",
        title: "AI-Hinweis zu Claim-Clustering in Review",
        summary: "Assist-Vorschlag wird manuell mit bestehendem Claim clm-1 abgeglichen.",
        sourceRoundSlug: "livestream-qa-stadtwerke",
        publicReason: "Moegliche Dublette wird vor Merge transparent geprueft.",
        internalReason: "Potenzieller Doppelpunkt; erst nach Redaktionsabgleich entscheiden.",
        reviewedBy: "editor@edebatte.local",
        reviewedAt: "2026-02-05T09:30:00.000Z",
        visibility: "management_only",
      },
      {
        id: "rl-3",
        status: "merged_into_existing_item",
        scope: "roadmap_action",
        entityId: "rm-2",
        title: "Counterposition-Task mit Session-Input zusammengefuehrt",
        summary: "Fragen aus Eventrunde wurden in Roadmap-Item rm-2 integriert.",
        sourceRoundSlug: "vor-ort-forum-energiepreise-neukoelln",
        appliedToId: "rm-2",
        publicReason: "Doppelte Folgefrage vermieden, bestehendes Item erweitert.",
        internalReason: "Gleicher inhaltlicher Schwerpunkt, zusammengefuehrt fuer bessere Nachverfolgbarkeit.",
        reviewedBy: "moderation@edebatte.local",
        reviewedAt: "2026-01-27T08:40:00.000Z",
        visibility: "public",
      },
      {
        id: "rl-4",
        status: "deferred_to_next_round",
        scope: "round_contribution",
        entityId: "rc-11",
        title: "Priorisierungsliste auf naechste Open Round vertagt",
        summary: "Follow-up-Task bleibt offen bis Evidenzmatrix aus Session vervollstaendigt ist.",
        sourceRoundSlug: "offene-runde-naechster-fokus",
        publicReason: "Entscheidung auf naechste Runde verschoben, um Datenluecken zu schliessen.",
        internalReason: "Abhaengig von externer Datennachreichung.",
        reviewedBy: "moderation@edebatte.local",
        reviewedAt: "2026-03-05T08:25:00.000Z",
        visibility: "public",
      },
      {
        id: "rl-5",
        status: "accepted_as_new_draft",
        scope: "claim_update",
        entityId: "clm-draft-4",
        title: "Neuer Claim-Entwurf zu Finanzierungspuffer",
        summary: "Rundenbeitrag wurde als neuer Draft-Claim in die interne Review uebernommen.",
        sourceRoundSlug: "podcast-expertenrunde-netzausbau",
        publicReason: "Neue Perspektive aufgenommen, noch nicht final verifiziert.",
        internalReason: "Sourcing laeuft, final erst nach Gegenposition.",
        reviewedBy: "redaktion@edebatte.local",
        reviewedAt: "2026-02-12T10:10:00.000Z",
        visibility: "management_only",
      },
    ],
    readinessChecks: [
      {
        id: "ready-1",
        createdAt: "2026-03-06T10:00:00.000Z",
        decidedBy: "moderation-board",
        decision: "needs_next_round",
        rationale:
          "Vote-Check wird erst empfohlen, wenn Kostenvergleich pro Quartier und Counterposition zum Sozialtarif geschlossen sind.",
      },
    ],
    exportSnapshot: {
      conciseSummary:
        "Topic im Status options_clarifying. Hauptkonflikte liegen bei Kostenannahmen, Sozialtarif-Kriterien und Verantwortlichkeit fuer Dashboard-Daten.",
      nextRoundAgenda: [
        "Kostenannahmen aus src-1 und src-3 harmonisieren",
        "Counterpositionen zum Sozialtarif strukturiert gegenueberstellen",
        "Verbindliche Datenzustaendigkeit fuer Dashboard festlegen",
      ],
      sourceSnapshot: [
        "src-1 official_document: Netzzustandsbericht Waerme 2025",
        "src-2 secondary_report: Sozialmonitor Energiearmut",
        "src-3 primary_source: Praxisanalyse Fernwaermeausfaelle",
        "src-4 community_note: Buergerpanel Vertrauen",
      ],
      roadmapSnapshot: [
        "rm-1 open evidence_missing",
        "rm-2 in_progress counterposition_missing",
        "rm-3 blocked authority_response_needed",
        "rm-4 open ready_for_vote_check",
      ],
      handoffNote:
        "Mandat-Handoff erst nach naechster Runde und dokumentierter Verantwortlichkeitszusage fuer Datenguete empfohlen.",
    },
    mandateBridge: {
      clarifiedNow: [
        "Prioritaere Quartiere fuer Netzsanierung sind eingegrenzt",
        "Mindestindikatoren fuer Sozialtarif-Pilot sind benannt",
      ],
      ownerNeeded: [
        "Verbindliche Datenpflege-Stelle fuer Dashboard",
        "Verantwortliche Stelle fuer Sozialtarif-Evaluation",
      ],
      openBeforeImplementation: [
        "Finanzierungspuffer bei steigenden Zinsen",
        "Counterpositionen zur Zielgruppendefinition",
      ],
      monitoringFocus: [
        "Ausfallquote je Quartier",
        "Haushaltsentlastung pro Zielgruppe",
        "Datenqualitaet und Publikationsrhythmus",
      ],
      linkedMandateId: "mandate-energy-berlin-2026-q2",
    },
  },
];

export const ROUND_SEED: Round[] = [
  {
    id: "rnd-article-1",
    slug: "artikel-kostenanalyse-waermenetze",
    topicSlug: "bezahlbare-energie-und-waermewende-berlin",
    title: "Artikelrunde: Kostenanalyse Waermenetze",
    type: "article",
    status: "closed",
    startedAt: "2026-01-18T09:00:00.000Z",
    sourceLabel: "Hintergrundartikel",
    sourceUrl: "https://example.org/artikel-waermenetze-kostenanalyse",
    sourcePublisher: "Lokalredaktion Berlin",
    summary:
      "Der Artikel hat Netzverluste und Investitionsstau fuer drei Quartiere offen gelegt. Schwerpunkt war Kostenentwicklung je Haushalt.",
    openPoints: [
      "Kostenannahmen fuer Materialpreise muessen aktualisiert werden.",
      "Vergleichsdaten zu alternativen Sanierungsfolgen fehlen.",
    ],
    contributions: [
      {
        id: "rc-1",
        type: "source",
        text: "Ergaenzender Verweis auf den Netzzustandsbericht 2025 mit Datentabelle pro Quartier.",
        authorLabel: "Buergerbeitrag",
        createdAt: "2026-01-18T11:20:00.000Z",
        reviewStatus: "merged_into_existing_item",
      },
      {
        id: "rc-2",
        type: "question",
        text: "Warum unterscheiden sich die Betriebskostenprognosen zwischen Nord und Ost so stark?",
        authorLabel: "Journalismus",
        createdAt: "2026-01-18T12:10:00.000Z",
        reviewStatus: "under_review",
      },
      {
        id: "rc-3",
        type: "objection",
        text: "Die angenommene Bauzeit wirkt zu optimistisch und ignoriert Engpaesse bei Fachfirmen.",
        authorLabel: "Fachverband Handwerk",
        createdAt: "2026-01-18T12:45:00.000Z",
        reviewStatus: "accepted_as_new_draft",
      },
    ],
  },
  {
    id: "rnd-event-1",
    slug: "vor-ort-forum-energiepreise-neukoelln",
    topicSlug: "bezahlbare-energie-und-waermewende-berlin",
    title: "Eventrunde: Vor-Ort-Forum Energiepreise in Neukoelln",
    type: "event",
    status: "closed",
    startedAt: "2026-01-25T16:30:00.000Z",
    sourceLabel: "Oeffentliches Forum",
    sourcePublisher: "Bezirksamt Neukoelln",
    summary:
      "Im Forum wurden Belastungsspitzen bei Mietnebenkosten gesammelt und priorisiert. Verwaltung und Stadtwerke haben offene Punkte mitgenommen.",
    openPoints: [
      "Definition fuer haushaltsnahe Entlastungsgrenzen fehlt.",
      "Rolle der Bezirke bei Zielgruppenansprache muss geklaert werden.",
    ],
    contributions: [
      {
        id: "rc-4",
        type: "perspective",
        text: "Viele Familien berichten ueber stark schwankende Abschlaege trotz konstantem Verbrauch.",
        authorLabel: "Bewohnerinitiative",
        createdAt: "2026-01-25T18:10:00.000Z",
        reviewStatus: "accepted_as_new_draft",
      },
      {
        id: "rc-5",
        type: "option",
        text: "Pilot mit quartiersbezogenem Sozialtarif plus verpflichtender Energieberatung.",
        authorLabel: "Sozialtraeger",
        createdAt: "2026-01-25T19:05:00.000Z",
        reviewStatus: "merged_into_existing_item",
      },
    ],
  },
  {
    id: "rnd-livestream-1",
    slug: "livestream-qa-stadtwerke",
    topicSlug: "bezahlbare-energie-und-waermewende-berlin",
    title: "Livestreamrunde: Q&A mit Stadtwerken",
    type: "livestream",
    status: "closed",
    startedAt: "2026-02-02T18:00:00.000Z",
    sourceLabel: "Livestream",
    sourceUrl: "https://example.org/livestream-stadtwerke-qa",
    sourcePublisher: "Stadtwerke Berlin",
    summary:
      "Im Livestream wurden Bauablauf, Ausfallrisiken und geplante Transparenzmassnahmen diskutiert. Mehrere Punkte wurden zur Nachpruefung markiert.",
    openPoints: [
      "Verbindliche Termine fuer monatliche Datenschnittstellen fehlen.",
      "Antwort zu Finanzierungspuffer ist unvollstaendig.",
    ],
    contributions: [
      {
        id: "rc-6",
        type: "summary_note",
        text: "Zentraler Konsens: Transparenz ueber Baustufen ist wichtiger als ein einzelner Endtermin.",
        authorLabel: "Moderation",
        createdAt: "2026-02-02T19:45:00.000Z",
        reviewStatus: "accepted_as_new_draft",
      },
      {
        id: "rc-7",
        type: "followup_task",
        text: "Stadtwerke liefern bis naechste Woche einen Datenfeldkatalog fuer das Fortschrittsdashboard.",
        authorLabel: "Redaktion",
        createdAt: "2026-02-02T19:52:00.000Z",
        reviewStatus: "under_review",
      },
    ],
  },
  {
    id: "rnd-video-1",
    slug: "video-erklaerung-sozialtarif",
    topicSlug: "bezahlbare-energie-und-waermewende-berlin",
    title: "Videorunde: Erklaerstueck Sozialtarif",
    type: "video",
    status: "closed",
    startedAt: "2026-02-07T08:30:00.000Z",
    sourceLabel: "Kurzvideo",
    sourceUrl: "https://example.org/video-sozialtarif-erklaert",
    sourcePublisher: "Kommunalkanal",
    summary:
      "Das Video hat Kriterien und Kritikpunkte zum Sozialtarif erklaert. In der Diskussion wurden mehrere Messindikatoren gefordert.",
    openPoints: [
      "Wie wird Mitnahmeeffekt im Pilot belastbar gemessen?",
      "Welche Exit-Regel gilt nach Ablauf der Pilotphase?",
    ],
    contributions: [
      {
        id: "rc-8",
        type: "protocol_note",
        text: "Diskussion protokolliert drei Mindestindikatoren: Ausfallquote, Haushaltsentlastung, Beratungsquote.",
        authorLabel: "Protokollteam",
        createdAt: "2026-02-07T10:05:00.000Z",
        reviewStatus: "merged_into_existing_item",
      },
    ],
  },
  {
    id: "rnd-podcast-1",
    slug: "podcast-expertenrunde-netzausbau",
    topicSlug: "bezahlbare-energie-und-waermewende-berlin",
    title: "Podcastrunde: Expertenrunde Netzausbau",
    type: "podcast",
    status: "closed",
    startedAt: "2026-02-11T13:00:00.000Z",
    sourceLabel: "Podcast Episode",
    sourceUrl: "https://example.org/podcast-netzausbau",
    sourcePublisher: "Stadtgespraeche",
    summary:
      "Fachgaeste haben Ausbaupfade, Finanzierungsmodelle und Verteilwirkungen gegenuebergestellt.",
    openPoints: [
      "Wie werden Randlagen in Priorisierung transparent beruecksichtigt?",
    ],
    contributions: [
      {
        id: "rc-9",
        type: "question",
        text: "Welche Finanzierungsmischung bleibt stabil, wenn Zinsszenarien steigen?",
        authorLabel: "Publikum",
        createdAt: "2026-02-11T14:20:00.000Z",
        reviewStatus: "accepted_as_new_draft",
      },
    ],
  },
  {
    id: "rnd-session-1",
    slug: "verwaltungssession-datenstandard",
    topicSlug: "bezahlbare-energie-und-waermewende-berlin",
    title: "Sessionrunde: Verwaltungsworkshop Datenstandard",
    type: "session",
    status: "open",
    startedAt: "2026-02-20T09:00:00.000Z",
    sourceLabel: "Fachsession",
    sourcePublisher: "Senatsverwaltung",
    summary:
      "Arbeitsgruppe zu Datenqualitaet und Reportingzyklen fuer das Topic-Dashboard. Runde ist noch offen fuer Nachreichungen.",
    openPoints: [
      "Versionierungsregel fuer Korrekturen muss festgelegt werden.",
      "Publikationsrhythmus ueber Feiertage ist offen.",
    ],
    contributions: [
      {
        id: "rc-10",
        type: "source",
        text: "Entwurf einer Datendefinitionstabelle mit Feldbeschreibungen und Validierungsregeln.",
        authorLabel: "IT-Leitstelle",
        createdAt: "2026-02-20T10:15:00.000Z",
        reviewStatus: "submitted",
      },
    ],
  },
  {
    id: "rnd-open-1",
    slug: "offene-runde-naechster-fokus",
    topicSlug: "bezahlbare-energie-und-waermewende-berlin",
    title: "Open Round: Naechster Fokus fuer das Topic",
    type: "open_round",
    status: "open",
    startedAt: "2026-03-04T17:30:00.000Z",
    sourceLabel: "Offene Beteiligungsrunde",
    summary:
      "Offene Runde fuer die Frage, welche Evidenz vor einem Vote-Check zwingend noch nachgereicht werden muss.",
    openPoints: [
      "Priorisierung der fehlenden Evidenz ist noch nicht abgeschlossen.",
      "Counterpositionen zum Sozialtarif muessen konsolidiert werden.",
    ],
    contributions: [
      {
        id: "rc-11",
        type: "followup_task",
        text: "Moderation erstellt bis zur naechsten Woche eine priorisierte Evidenzliste fuer den Vote-Check.",
        authorLabel: "Moderation",
        createdAt: "2026-03-04T19:00:00.000Z",
        reviewStatus: "deferred_to_next_round",
      },
    ],
  },
];
