"use client";

import Link from "next/link";
import { useLocale } from "@/context/LocaleContext";
import type { StartExperienceModel } from "@/features/start/startExperience";
import { buildFreeBallotStartHref, GO_TO_MARKET_PACKAGING } from "@features/pricing/goToMarketPackaging";
import { HomeBallotExperience } from "./HomeBallotExperience";

type Props = { experience: StartExperienceModel };

export default function HomeGoToMarketLanding({ experience }: Props) {
  const { locale } = useLocale();
  const de = locale === "de";
  const cta = de ? "Kostenlos starten" : "Start for free";
  const jobs = de ? [["Entscheiden","Optionen vergleichen, neue Vorschläge aufnehmen und Prioritäten sichtbar machen."],["Zuhören","Mitarbeiter-, Kunden- oder Mitgliederperspektiven strukturiert einsammeln."],["Priorisieren","Viele Hinweise oder Ideen ordnen und erkennen, was trägt, strittig ist oder fehlt."],["Recherchieren","Leserfragen, Erfahrungen, Hinweise und Quellen strukturiert sammeln."]] : [["Decide","Compare options, capture new proposals and reveal priorities."],["Listen","Gather employee, customer or member perspectives in a structured way."],["Prioritise","Structure ideas and reveal what carries, conflicts or is missing."],["Research","Collect reader questions, experiences, tips and sources."]];
  return <div className="overflow-hidden bg-[color:var(--background)] text-[color:var(--foreground)]">
    <section className="relative border-b border-[color:var(--border)]"><div aria-hidden="true" className="absolute inset-0 bg-[radial-gradient(circle_at_50%_12%,rgba(34,211,238,0.18),transparent_31%)]"/><div className="relative mx-auto max-w-[76rem] px-5 py-14 sm:px-8 lg:px-10"><div className="mx-auto max-w-4xl text-center"><p className="text-xs font-black uppercase tracking-[0.2em] text-cyan-700 dark:text-cyan-300">{de ? "Damit nicht Lautstärke entscheidet." : "So volume does not decide."}</p><h1 className="mt-5 text-balance text-4xl font-black leading-[1.01] tracking-[-0.04em] sm:text-6xl lg:text-7xl">{de ? "Eine Frage. Viele Perspektiven. Ein klareres Bild." : "One question. Many perspectives. A clearer picture."}</h1><p className="mx-auto mt-5 max-w-3xl text-lg leading-8 text-[color:var(--muted)] sm:text-xl">{de ? "eDebatte beginnt so einfach wie eine Abstimmung – und hilft danach zu verstehen, was Menschen wirklich beitragen: Positionen, neue Vorschläge, Gründe, Erfahrungen, Quellen und offene Fragen." : "eDebatte starts as simply as a ballot, then helps you understand positions, proposals, reasons, experiences, sources and open questions."}</p></div><div className="mx-auto mt-10 max-w-4xl"><HomeBallotExperience /></div>
    <div className="mx-auto mt-9 grid max-w-4xl gap-4 md:grid-cols-2"><Link href={buildFreeBallotStartHref(undefined,"homepage-question")} className="group rounded-[1.75rem] border border-cyan-500/40 bg-cyan-500/5 p-6 transition hover:-translate-y-0.5"><p className="text-xs font-black uppercase tracking-[0.16em] text-cyan-700 dark:text-cyan-300">{de ? "Sofort starten" : "Start now"}</p><h2 className="mt-2 text-2xl font-black">{de ? "Eine Frage stellen" : "Ask one question"}</h2><p className="mt-2 text-sm leading-6 text-[color:var(--muted)]">{de ? "Frage formulieren, Startantworten festlegen, Voxy wählen und direkt teilen." : "Write the question, set starting answers, choose Voxy and share."}</p><span className="mt-5 inline-block font-black text-cyan-700 dark:text-cyan-300">{cta} →</span></Link><div className="rounded-[1.75rem] border border-[color:var(--border)] p-6"><div className="flex items-center justify-between gap-3"><p className="text-xs font-black uppercase tracking-[0.16em] text-cyan-700 dark:text-cyan-300">Premium</p><span className="rounded-full border border-[color:var(--border)] px-2.5 py-1 text-[10px] font-black uppercase text-[color:var(--muted)]">{de ? "In Vorbereitung" : "Coming"}</span></div><h2 className="mt-2 text-2xl font-black">{de ? "Viele Fragen aus einem Dokument" : "Many questions from one document"}</h2><p className="mt-2 text-sm leading-6 text-[color:var(--muted)]">{de ? "Parteiprogramm, Studie, Vereins-, Verbands- oder Unternehmensunterlagen hochladen. eDebatte soll daraus mehrere Fragen und mögliche Antworten zur Prüfung vorbereiten – bevor etwas veröffentlicht wird." : "Upload a programme, study or organisation document. eDebatte is being prepared to turn it into multiple questions and possible answers for review before anything is published."}</p><p className="mt-4 text-xs leading-5 text-[color:var(--muted)]">{de ? "Der vorhandene Upload nimmt derzeit Material reviewpflichtig an; automatische Extraktion und Fragenerzeugung werden erst nach produktiver Freigabe aktiviert." : "The current upload accepts material for review; automatic extraction and question generation will only be enabled once production-ready."}</p></div></div>
    <p className="mt-5 text-center text-xs font-semibold text-[color:var(--muted)]">{de ? `Bis ${GO_TO_MARKET_PACKAGING.freeParticipantGuideline} Teilnehmende kostenlos` : `Free up to ${GO_TO_MARKET_PACKAGING.freeParticipantGuideline} participants`}</p>{experience.workspaceHref && experience.workspaceLabel ? <div className="mt-3 text-center"><Link href={experience.workspaceHref} className="text-xs font-semibold text-cyan-700 hover:underline dark:text-cyan-300">{experience.workspaceLabel}</Link></div> : null}</div></section>
    <section className="bg-slate-950 py-16 text-white"><div className="mx-auto max-w-[76rem] px-5 sm:px-8 lg:px-10"><h2 className="max-w-3xl text-3xl font-black sm:text-5xl">{de ? "Nicht nur Antworten sammeln. Verstehen, was dahinterliegt." : "Do not just collect answers. Understand what sits behind them."}</h2><div className="mt-10 border-y border-white/15 md:grid md:grid-cols-4 md:divide-x md:divide-white/15">{jobs.map(([title,body],i)=><div key={title} className="py-6 md:px-6 md:py-8"><span className="text-xs font-black text-cyan-300">0{i+1}</span><h3 className="mt-2 text-xl font-bold">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-300">{body}</p></div>)}</div></div></section>
    <section className="mx-auto max-w-[76rem] px-5 py-16 sm:px-8 lg:px-10"><div className="grid gap-10 lg:grid-cols-2"><div><h2 className="text-3xl font-black sm:text-5xl">{de ? "Einfach anfangen. Tiefe entsteht erst, wenn du sie brauchst." : "Start simple. Add depth when you need it."}</h2><p className="mt-5 text-base leading-7 text-[color:var(--muted)]">{de ? "Frage stellen, Menschen einladen und anschließend nicht nur zählen, sondern Gründe, neue Vorschläge, Erfahrungen und Quellen sichtbar machen." : "Ask, invite and then see more than counts: reasons, proposals, experiences and sources."}</p></div><div className="border-l-2 border-cyan-400 pl-6"><h3 className="text-xl font-bold">{de ? "Du bestimmst, was passiert." : "You decide what happens."}</h3><ul className="mt-4 space-y-3 text-sm leading-6 text-[color:var(--muted)]"><li>{de ? "Nichts geht automatisch online." : "Nothing goes online automatically."}</li><li>{de ? "Voxy bleibt optional und muss bewusst gewählt werden." : "Voxy remains optional and requires an explicit choice."}</li><li>{de ? "Fakten werden nicht zur Abstimmung gestellt." : "Facts are not put to a vote."}</li><li>{de ? "Gemeinsames Lernen soll anonymisiert und ohne persönliche Profile erfolgen." : "Shared learning is designed to be anonymised and without personal profiles."}</li></ul></div></div></section>
    <section className="border-t border-[color:var(--border)] px-5 py-16 text-center"><h2 className="mx-auto max-w-4xl text-3xl font-black sm:text-5xl">{de ? "Welche Frage willst du nicht länger nur im Raum stehen lassen?" : "Which question do you no longer want to leave hanging?"}</h2><Link href={buildFreeBallotStartHref(undefined,"homepage-final")} className="mt-7 inline-flex min-h-14 items-center rounded-full bg-cyan-500 px-8 py-3.5 font-black text-slate-950">{cta} →</Link></section>
  </div>;
}
