import type { EDebattePackageDefinition, EDebattePackageId, PackageAudience, PackageStatus } from "./types";

export const PACKAGE_STATUS_LABELS: Record<PackageStatus, string> = {
  verfuegbar: "Direkt verfügbar",
  pilot: "Pilotbetrieb",
  vormerkung: "Bestellbar",
  bald: "In Vorbereitung",
};

export const PACKAGE_AUDIENCE_LABELS: Record<PackageAudience, string> = {
  buerger: "Privat",
  journalismus: "Freie Journalist:innen",
  organisation: "Organisationen und Kommunen",
};

export const EDEBATTE_PACKAGES_DE: EDebattePackageDefinition[] = [
  {
    id: "basis",
    titel: "eDebatte Interessiert",
    zielgruppe: "Privat",
    typ: "buerger",
    status: "verfuegbar",
    preisMonat: 4.99,
    preisLabel: "4,99 € / Monat inkl. MwSt. · jährliche Zahlung bevorzugt",
    fuerWen: "Für Menschen, die ein Anliegen niedrigschwellig einbringen möchten.",
    wofuerGedacht: "Beitragen: Anliegen einbringen, Themen zuordnen und Relevanz nachvollziehen.",
    unterschiedZurNaechstenStufe: "Aktiv ergänzt den Modus Prüfen für Texte, Agenden und Berichte.",
    beschreibungKurz:
      "Der offene Einstieg: Hinweise, Beobachtungen und Claims einbringen und nachvollziehbar einordnen lassen.",
    leistungen: [
      "Anliegen, Hinweise, Beobachtungen und Claims einreichen",
      "Themengebiet wird erkannt und bestehenden Kontexten zugeordnet",
      "Benachrichtigung, wenn daraus ein relevanter Pfad in Streams, Resonanz oder Swipes entsteht",
      "Demokratische Rechte bleiben unabhängig vom Paket gleich",
    ],
    ctaText: "Beitragen",
    ctaHref: "/order?paket=basis",
    contributionCreditsPerMonth: 1,
    anlassraumCredits: 0,
    searchCredits: 0,
    deepResearchCredits: 0,
    dossierBoostEligible: false,
    premiumResearchEligible: false,
  },
  {
    id: "start",
    titel: "eDebatte Aktiv",
    zielgruppe: "Privat",
    typ: "buerger",
    status: "verfuegbar",
    preisMonat: 14.99,
    preisLabel: "14,99 € / Monat inkl. MwSt. · jährliche Zahlung bevorzugt",
    fuerWen: "Für Menschen, die vorhandene Texte und Agenden professionell prüfen wollen.",
    wofuerGedacht: "Prüfen: Beiträge, Texte, Agenden und Berichte auf Abstimmungsfähigkeit einordnen.",
    unterschiedZurNaechstenStufe: "Mitgestaltend ergänzt den Modus Entwerfen für gemeinsame Ausarbeitung.",
    beschreibungKurz:
      "Originaltexte bleiben erhalten und werden um Prüfstellen, Eignungshinweise und Resonanzoptionen ergänzt.",
    leistungen: [
      "3 Beiträge pro Monat",
      "1 Anlassraum inklusive",
      "Agenda, Artikel oder Beitrag auf Abstimmungsfähigkeit prüfen",
      "Richtlinien-, Prüf- und Companion-Hinweise ohne Umschreibung",
      "Kein automatischer externer Search- oder Deep-Research-Aufruf",
      "Faktencheck und weitere Add-ons optional zuschaltbar",
    ],
    hervorgehoben: true,
    ctaText: "Prüfen",
    ctaHref: "/order?paket=start",
    contributionCreditsPerMonth: 3,
    anlassraumCredits: 1,
    searchCredits: 0,
    deepResearchCredits: 0,
    dossierBoostEligible: true,
    premiumResearchEligible: false,
  },
  {
    id: "pro",
    titel: "eDebatte Mitgestaltend",
    zielgruppe: "Privat",
    typ: "buerger",
    status: "verfuegbar",
    preisMonat: 29.99,
    preisLabel: "29,99 € / Monat inkl. MwSt. · jährliche Zahlung bevorzugt",
    fuerWen: "Für Menschen, die Themen gemeinsam und belastbar ausarbeiten wollen.",
    wofuerGedacht: "Entwerfen: Themen gemeinsam mit Guided Flow und Human Loop ausarbeiten.",
    unterschiedZurNaechstenStufe: "Höchste private Erarbeitungstiefe im aktuellen Modell.",
    beschreibungKurz:
      "Der tiefe Arbeitsmodus für gemeinsame Ausarbeitung mit Rückfragen, Verdichtung und belastbarem Arbeitsstand.",
    leistungen: [
      "10 Beiträge pro Monat",
      "1 Anlassraum inklusive",
      "1 Entwicklungsthema inklusive",
      "Optional 1 Search Credit, sobald Provider-/Kosten-Policy aktiv ist",
      "Geführter Flow mit Rückfragen und iterativer Verdichtung",
      "Human-Loop-gestützte Ausarbeitung Richtung Dossier",
      "Konfliktlinien, offene Punkte und Alternativen systematisch sichtbar machen",
      "Deep Research ist nur als optionales Premium-Add-on vorgesehen",
    ],
    ctaText: "Entwerfen",
    ctaHref: "/order?paket=pro",
    contributionCreditsPerMonth: 10,
    anlassraumCredits: 1,
    searchCredits: 1,
    deepResearchCredits: 0,
    dossierBoostEligible: true,
    premiumResearchEligible: true,
  },
  {
    id: "journal_basis",
    titel: "Journalismus Fokus",
    zielgruppe: "Freie Journalist:innen",
    typ: "journalismus",
    status: "vormerkung",
    preisLabel: "Aktivierung im redaktionellen Betriebsmodell",
    fuerWen: "Für freie Journalist:innen mit Fokus auf nachvollziehbare Recherche.",
    wofuerGedacht: "Anlassraum plus offenes Dossier als redaktioneller Kern.",
    unterschiedZurNaechstenStufe: "Plus ergänzt optionales Faktencheck-Kontingent und mehr Begleitung.",
    beschreibungKurz:
      "Recherche, Anlassraum, Dossier und Öffentlichkeit nachvollziehbar öffnen.",
    leistungen: [
      "Einstiegskontingent: 3 Beiträge pro Monat und 1 Anlassraum",
      "Offener Anlassraum zu Recherche, Beitrag oder Format",
      "Offenes Dossier mit sichtbarer Quellen- und Fragenlage",
      "QR- und Companion-Nutzung rund um Artikel, Podcast, Video oder Sendung",
      "Nachvollziehbare Einbindung von Öffentlichkeit statt Kommentar-Chaos",
    ],
    ctaText: "Jetzt bestellen",
    ctaHref: "/order?paket=journal_basis",
    contributionCreditsPerMonth: 3,
    anlassraumCredits: 1,
    searchCredits: 0,
    deepResearchCredits: 0,
    dossierBoostEligible: true,
    premiumResearchEligible: false,
  },
  {
    id: "journal_pro",
    titel: "Journalismus Plus",
    zielgruppe: "Freie Journalist:innen",
    typ: "journalismus",
    status: "vormerkung",
    preisLabel: "Aktivierung im redaktionellen Betriebsmodell",
    fuerWen: "Für freie Journalist:innen mit höherem Produktions- und Prüfbedarf.",
    wofuerGedacht: "Anlassraum, Dossier, Companion/QR und vertiefte Einordnung.",
    unterschiedZurNaechstenStufe: "Umfasst optionales Faktencheck-Kontingent und engere Begleitung.",
    beschreibungKurz:
      "Für vertiefte journalistische Arbeit mit zusätzlicher professioneller Begleitung.",
    leistungen: [
      "Arbeitskontingent: 10 Beiträge pro Monat und 1 Anlassraum",
      "Vertiefte Quellen-, Fragen- und Widerspruchslagen",
      "Strukturierte Anschlussfähigkeit für öffentliche Debatte",
      "Companion-Formate für Redaktion und Publikum",
      "Optionales Faktencheck-Kontingent für strittige Behauptungen",
    ],
    hervorgehoben: true,
    ctaText: "Jetzt bestellen",
    ctaHref: "/order?paket=journal_pro",
    contributionCreditsPerMonth: 10,
    anlassraumCredits: 1,
    searchCredits: 1,
    deepResearchCredits: 0,
    dossierBoostEligible: true,
    premiumResearchEligible: true,
  },
  {
    id: "b2b_basis",
    titel: "Organisation Aktivierung",
    zielgruppe: "Organisationen",
    typ: "organisation",
    status: "vormerkung",
    preisLabel: "ab 1.500 € / Monat zzgl. MwSt. · Aktivierung · jährliche Zahlung bevorzugt",
    fuerWen: "Für Organisationen, Verbände und Vereine mit professionellem Einstieg.",
    wofuerGedacht: "Teams, Rollen und Governance stabil aufsetzen.",
    unterschiedZurNaechstenStufe: "Betrieb Plus erweitert laufende Governance- und Reporttiefe.",
    beschreibungKurz:
      "Strukturierte Beteiligung mit professionellem Betriebsrahmen statt politischem Sonderzugang.",
    leistungen: [
      "Einstiegskontingent für kleine Vereine: 3 Beiträge pro Monat und 1 Anlassraum",
      "Themenräume und Anlassräume",
      "Strukturierte Beteiligung mit Teams und Rollen",
      "Governance, Moderation und Routing",
      "Reports, Outcomes und Auswertung",
    ],
    ctaText: "Bestellung absenden",
    ctaHref: "/order?paket=b2b_basis",
    contributionCreditsPerMonth: 3,
    anlassraumCredits: 1,
    searchCredits: 0,
    deepResearchCredits: 0,
    dossierBoostEligible: true,
    premiumResearchEligible: false,
  },
  {
    id: "b2b_pro",
    titel: "Organisation Betrieb Plus",
    zielgruppe: "Organisationen",
    typ: "organisation",
    status: "vormerkung",
    preisLabel: "ab 2.900 € / Monat zzgl. MwSt. · Betrieb Plus · jährliche Zahlung bevorzugt",
    fuerWen: "Für Organisationen mit dauerhaftem, mehrspurigem Betrieb.",
    wofuerGedacht: "Laufende Governance, Routing und auswertbare Prozesse.",
    unterschiedZurNaechstenStufe: "Vertiefte Reports und Begleitungsleistung im Regelbetrieb.",
    beschreibungKurz:
      "Für laufenden Betrieb mit mehreren Teams und vertiefter Governance-Begleitung.",
    leistungen: [
      "Mehrere parallel betreute Beteiligungskontexte",
      "Vertiefte Rollen-, Moderations- und Routingabläufe",
      "Erweiterte Reports und Outcomes",
      "Optionale Managed-Governance-Unterstützung",
    ],
    hervorgehoben: true,
    ctaText: "Bestellung absenden",
    ctaHref: "/order?paket=b2b_pro",
    contributionCreditsPerMonth: 0,
    anlassraumCredits: 0,
    searchCredits: 0,
    deepResearchCredits: 0,
    dossierBoostEligible: true,
    premiumResearchEligible: true,
  },
  {
    id: "b2g_basis",
    titel: "Kommune / Verwaltung Aktivierung",
    zielgruppe: "Kommunen / Verwaltung",
    typ: "organisation",
    status: "vormerkung",
    preisLabel: "ab 2.500 € / Monat zzgl. MwSt. · Aktivierung · jährliche Zahlung bevorzugt",
    fuerWen: "Für Kommunen und Verwaltungen mit erstem Beteiligungsbetrieb.",
    wofuerGedacht: "Anlassräume, Transparenz und klare Rückläufe aufbauen.",
    unterschiedZurNaechstenStufe: "Betrieb Plus stärkt Auswertung, Reports und fortlaufende Umsetzung.",
    beschreibungKurz:
      "Transparente Struktur für kommunale Beteiligung mit klarer Governance und belastbaren Rückläufen.",
    leistungen: [
      "Beteiligungsbetrieb mit Anlassräumen und Themenräumen",
      "Transparenz und nachvollziehbare Governance",
      "Rückläufe und Reports für Verwaltung und Öffentlichkeit",
      "Anonymisierte Mehrheits-, Minderheits- und Spannungsbilder",
    ],
    ctaText: "Bestellung absenden",
    ctaHref: "/order?paket=b2g_basis",
    contributionCreditsPerMonth: 0,
    anlassraumCredits: 0,
    searchCredits: 0,
    deepResearchCredits: 0,
    dossierBoostEligible: true,
    premiumResearchEligible: true,
  },
  {
    id: "b2g_pro",
    titel: "Kommune / Verwaltung Betrieb Plus",
    zielgruppe: "Kommunen / Verwaltung",
    typ: "organisation",
    status: "vormerkung",
    preisLabel: "ab 4.500 € / Monat zzgl. MwSt. · Betrieb Plus · jährliche Zahlung bevorzugt",
    fuerWen: "Für Kommunen mit fortlaufendem Beteiligungs- und Auswertungsbetrieb.",
    wofuerGedacht: "Skalierte Prozesse mit stärkerer Ergebnis- und Umsetzungsnähe.",
    unterschiedZurNaechstenStufe: "Umfasst die höchste kommunale Ausbaustufe im aktuellen Modell.",
    beschreibungKurz:
      "Für fortlaufenden Beteiligungsbetrieb mit vertiefter Begleitung, Reports und Umsetzungsnähe.",
    leistungen: [
      "Skalierter Beteiligungsbetrieb über mehrere Kontexte",
      "Vertiefte Governance- und Moderationsunterstützung",
      "Erweiterte Ergebnis- und Umsetzungsreports",
      "Optionale Add-ons für Kommunikation und Betriebsführung",
    ],
    hervorgehoben: true,
    ctaText: "Bestellung absenden",
    ctaHref: "/order?paket=b2g_pro",
    contributionCreditsPerMonth: 0,
    anlassraumCredits: 0,
    searchCredits: 0,
    deepResearchCredits: 0,
    dossierBoostEligible: true,
    premiumResearchEligible: true,
  },
];

export const EDEBATTE_PACKAGE_IDS: EDebattePackageId[] = EDEBATTE_PACKAGES_DE.map((pkg) => pkg.id);
