import type { EDebattePackageDefinition } from "./types";

export const EDEBATTE_PACKAGES_EN: EDebattePackageDefinition[] = [
  {
    id: "basis",
    titel: "eDebatte Interested",
    zielgruppe: "Civic",
    typ: "buerger",
    status: "verfuegbar",
    preisMonat: 3.99,
    mitgliederPreisMonat: 0,
    preisLabel: "€0 for VoiceOpenGov members · €3.99 regular",
    fuerWen: "For people who want to submit issues with a low-friction start.",
    wofuerGedacht: "Contribute: submit concerns, route topics and keep relevance visible.",
    unterschiedZurNaechstenStufe: "Active adds the review mode for texts, agendas and reports.",
    beschreibungKurz:
      "The open entry path for claims, observations and signals with transparent categorization.",
    leistungen: [
      "Submit concerns, observations and claims",
      "Automatic topic recognition and context matching",
      "Get informed when a submission opens a relevant path in streams, resonance or swipes",
      "Democratic rights remain equal across all packages",
    ],
    ctaText: "Contribute",
    ctaHref: "/order?paket=basis",
  },
  {
    id: "start",
    titel: "eDebatte Active",
    zielgruppe: "Civic",
    typ: "buerger",
    status: "verfuegbar",
    preisMonat: 9.9,
    preisLabel: "€9.90",
    fuerWen: "For people who want a professional check of existing texts and agendas.",
    wofuerGedacht: "Review: check contributions, texts, agendas and reports for vote readiness.",
    unterschiedZurNaechstenStufe: "Co-creating adds the drafting mode for collaborative elaboration.",
    beschreibungKurz:
      "Keep original text intact and add review signals, policy hints and resonance options.",
    leistungen: [
      "Check article, agenda or contribution for vote eligibility",
      "Companion-style policy and review guidance without rewriting",
      "Optionally open issue room, swipes and resonance for participation",
      "Fact-check and further add-ons can be enabled optionally",
    ],
    hervorgehoben: true,
    ctaText: "Review",
    ctaHref: "/order?paket=start",
  },
  {
    id: "pro",
    titel: "eDebatte Co-creating",
    zielgruppe: "Civic",
    typ: "buerger",
    status: "verfuegbar",
    preisMonat: 29.9,
    preisLabel: "€29.90",
    fuerWen: "For people who want to collaboratively develop topics in depth.",
    wofuerGedacht: "Draft together: develop topics with guided flow and human loop.",
    unterschiedZurNaechstenStufe: "Highest private working depth in the current model.",
    beschreibungKurz:
      "Deep working mode with guided questions, structured synthesis and resilient topic progression.",
    leistungen: [
      "Guided flow with iterative questions and refinement",
      "Human-loop collaboration toward a robust dossier state",
      "Explicit handling of conflicts, alternatives and open issues",
      "Higher-quality mode with optional add-ons for longer civic processes",
    ],
    ctaText: "Draft",
    ctaHref: "/order?paket=pro",
  },
  {
    id: "journal_basis",
    titel: "Journalism Focus",
    zielgruppe: "Independent journalists",
    typ: "journalismus",
    status: "vormerkung",
    preisLabel: "Activation within the editorial operating model",
    fuerWen: "For independent journalists focused on transparent research.",
    wofuerGedacht: "Issue room plus open dossier as the editorial core.",
    unterschiedZurNaechstenStufe: "Plus adds optional fact-check quota and more support.",
    beschreibungKurz:
      "Open research, issue room, dossier and public continuity in one professional workflow.",
    leistungen: [
      "Open issue room for research, article or format",
      "Open dossier with visible source and question context",
      "QR and companion usage around article, podcast, video or broadcast",
      "Traceable public integration instead of comment chaos",
    ],
    ctaText: "Order now",
    ctaHref: "/order?paket=journal_basis",
  },
  {
    id: "journal_pro",
    titel: "Journalism Plus",
    zielgruppe: "Independent journalists",
    typ: "journalismus",
    status: "vormerkung",
    preisLabel: "Activation within the editorial operating model",
    fuerWen: "For independent journalists with higher production and review needs.",
    wofuerGedacht: "Issue room, dossier, companion/QR and deeper framing.",
    unterschiedZurNaechstenStufe: "Includes optional fact-check quota and closer support.",
    beschreibungKurz:
      "For deeper editorial work with additional professional guidance.",
    leistungen: [
      "Deeper source, question and contradiction context",
      "Stronger public follow-up and debate continuity",
      "Companion formats for newsroom and audience",
      "Optional fact-check quota for disputed claims",
    ],
    hervorgehoben: true,
    ctaText: "Order now",
    ctaHref: "/order?paket=journal_pro",
  },
  {
    id: "b2b_basis",
    titel: "Organization Activation",
    zielgruppe: "Organizations",
    typ: "organisation",
    status: "vormerkung",
    preisLabel: "from €1,500 / month · activation",
    fuerWen: "For organizations, associations and non-profits entering professionally.",
    wofuerGedacht: "Set up teams, roles and governance reliably.",
    unterschiedZurNaechstenStufe: "Operations Plus expands ongoing governance and reporting depth.",
    beschreibungKurz:
      "Structured participation with a professional operating framework, not political privileged access.",
    leistungen: [
      "Topic rooms and issue rooms",
      "Structured participation with teams and roles",
      "Governance, moderation and routing",
      "Reports, outcomes and analysis",
    ],
    ctaText: "Submit order",
    ctaHref: "/order?paket=b2b_basis",
  },
  {
    id: "b2b_pro",
    titel: "Organization Operations Plus",
    zielgruppe: "Organizations",
    typ: "organisation",
    status: "vormerkung",
    preisLabel: "from €2,900 / month · operations plus",
    fuerWen: "For organizations with continuous, multi-track operations.",
    wofuerGedacht: "Ongoing governance, routing and analyzable processes.",
    unterschiedZurNaechstenStufe: "Deeper reports and support intensity in regular operations.",
    beschreibungKurz:
      "For ongoing operations with multiple teams and deeper governance support.",
    leistungen: [
      "Multiple parallel participation contexts",
      "Deeper role, moderation and routing workflows",
      "Extended reports and outcomes",
      "Optional managed governance support",
    ],
    hervorgehoben: true,
    ctaText: "Submit order",
    ctaHref: "/order?paket=b2b_pro",
  },
  {
    id: "b2g_basis",
    titel: "Municipality / Administration Activation",
    zielgruppe: "Municipalities / administration",
    typ: "organisation",
    status: "vormerkung",
    preisLabel: "from €2,500 / month · activation",
    fuerWen: "For municipalities and administrations starting participation operations.",
    wofuerGedacht: "Build issue rooms, transparency and clear feedback loops.",
    unterschiedZurNaechstenStufe: "Operations Plus strengthens analysis, reports and ongoing implementation.",
    beschreibungKurz:
      "Transparent structure for municipal participation with clear governance and reliable feedback loops.",
    leistungen: [
      "Participation operations with issue and topic rooms",
      "Transparency and traceable governance",
      "Feedback loops and reports for administration and public",
      "Anonymized majority, minority and tension insights",
    ],
    ctaText: "Submit order",
    ctaHref: "/order?paket=b2g_basis",
  },
  {
    id: "b2g_pro",
    titel: "Municipality / Administration Operations Plus",
    zielgruppe: "Municipalities / administration",
    typ: "organisation",
    status: "vormerkung",
    preisLabel: "from €4,500 / month · operations plus",
    fuerWen: "For municipalities with continuous participation and analysis operations.",
    wofuerGedacht: "Scale processes with stronger outcome and implementation proximity.",
    unterschiedZurNaechstenStufe: "Highest municipal package in the current model.",
    beschreibungKurz:
      "For continuous participation operations with deeper support, reports and implementation proximity.",
    leistungen: [
      "Scaled participation operations across multiple contexts",
      "Deeper governance and moderation support",
      "Extended outcome and implementation reports",
      "Optional add-ons for communication and operations",
    ],
    hervorgehoben: true,
    ctaText: "Submit order",
    ctaHref: "/order?paket=b2g_pro",
  },
];
