import type { SelfServiceOrgOnboardingRequest } from "@/features/organization/selfServiceOrgOnboardingContract";

const CREATED_AT = "2026-06-27T09:00:00.000Z";
const UPDATED_AT = "2026-06-27T12:00:00.000Z";

export const SELF_SERVICE_ORG_ONBOARDING_FIXTURES = {
  municipalityPendingOperatorReview: {
    id: "self-service-municipality-1",
    organizationName: "Stadt Beispielstadt",
    applicantType: "municipality",
    useCases: ["participation_space", "source_monitoring"],
    contactName: "Mara Beispiel",
    contactEmail: "mara@beispielstadt.de",
    websiteUrl: "https://beispielstadt.de",
    registerReference: null,
    region: "kommune-beispielstadt",
    requestedEntitlements: ["member_workspace", "partner_workspace"],
    verificationStatus: "pending_operator_review",
    provisioningStatus: "requested",
    reviewStatus: "submitted",
    openQuestions: [],
    createdAt: CREATED_AT,
    updatedAt: UPDATED_AT,
  } satisfies SelfServiceOrgOnboardingRequest,
  associationNeedsInformation: {
    id: "self-service-association-1",
    organizationName: "Verein Bildungsdialog",
    applicantType: "association",
    useCases: ["voxy_cocreation"],
    contactName: "Lea Beispiel",
    contactEmail: "kontakt@bildungsdialog.example",
    websiteUrl: null,
    registerReference: null,
    region: "berlin",
    requestedEntitlements: ["author_plus"],
    verificationStatus: "needs_information",
    provisioningStatus: "requested",
    reviewStatus: "needs_clarification",
    openQuestions: ["Bitte Nachweis zur Organisationsform ergänzen."],
    createdAt: CREATED_AT,
    updatedAt: UPDATED_AT,
  } satisfies SelfServiceOrgOnboardingRequest,
  mediaPartnerApprovedForSetup: {
    id: "self-service-media-1",
    organizationName: "Lokalredaktion Mitte",
    applicantType: "media_partner",
    useCases: ["partner_distribution", "live_campaign"],
    contactName: "Nora Beispiel",
    contactEmail: "redaktion@lokalredaktion.example",
    websiteUrl: "https://lokalredaktion.example",
    registerReference: "handelsregister-hrb-1234",
    region: "berlin-mitte",
    requestedEntitlements: ["partner_workspace", "admin_managed"],
    verificationStatus: "verified",
    provisioningStatus: "requested",
    reviewStatus: "approved_for_setup",
    openQuestions: [],
    createdAt: CREATED_AT,
    updatedAt: UPDATED_AT,
  } satisfies SelfServiceOrgOnboardingRequest,
} as const;
