export {
  UNLIMITED_LIMIT,
  CONTRIBUTION_LIMITS_PER_MONTH,
  STREAM_LIMITS_PER_MONTH,
  CAMPAIGN_LIMITS_PER_MONTH,
  QUESTIONS_PER_CAMPAIGN_LIMITS,
  REPORT_SCOPE,
  type ReportScope,
} from "../apps/web/src/config/limits";
